# -*- coding: utf-8 -*-
"""week3_demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KpbpLBftgzYKlKuCXBbv7we42OzZJ5MJ

from google colab import files #匯入套件

import pandas as pd

upload = files.upload() #開啟上傳介面並載入

data = pd.read_csv("剛剛上傳的檔案名稱")
"""

from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

import os
os.chdir("/content/gdrive/My Drive//實務分析/") # 切換目錄
#!ls -l "/content/gdrive/My Drive/112_2_LATIA/week3_030524/" # 列出目錄下的檔案
!ls -l "112_student.csv"

import pandas as pd

#csv_file = './112_student.csv'
csv_file ="112_student.csv"

#columns = [
#    "學年度","學校代碼","學校名稱","日間∕進修別","等級別","總計","男生計",
#    "女生計","一年級男","一年級女","二年級男","二年級女","三年級男","三年級女",
#    "四年級男","四年級女","五年級男","五年級女","六年級男","六年級女",
#    "七年級男","七年級女","延修生男","延修生女","縣市名稱","體系別"
#]
df = pd.read_csv(csv_file) # 讀取csv檔案
print(df.head())

#查看資料欄位資訊
print(df.info())

#查看資料的統計學資訊描述
#print(df.describe(include='all'))

"""# 1.哪間大專院校有最多的學士生

step1: 取出想要查看的欄位，並印出此資料集共有多少筆紀錄 (len)

step2: 篩選等級別為"B 學士"的DataFrame，並印出有招生學士學制的學校數量

step3: 依據"總計"從大到小排序並印出結果 (sort_values, by, ascending)
"""

# 請在"填空"處，輸入所需要的指令或參數

df1 = df[['等級別','總計','學校名稱']] # 取出想要觀看的欄位
print("本資料集共有", len(df1), "筆紀錄")

df1_1 = df1[df1['等級別'] == 'B 學士']
print("有招生學士學制的學校數量為",len(df1_1), "\n")
df1_1_sorted = df1_1.sort_values(by="總計",ascending=False)
print("112學年度在籍的學士生最多人數之學校為", df1_1_sorted.head(1)['學校名稱'].values)

"""# 2. 國立？所；私立？所

step1: 建立空字串 (lsit=[])

step2: 建立for迴圈，配合if else條件，取出國立與私立

step3: 新增「公私立」column在DataFrame中 (df['公私立'])

step4: 篩選掉重複的學校代碼資料 (drop_duplicates)

step5: 計算公立與私立學校的筆數，並印出結果 (value_counts)
"""

type_list = [] # 建立空字串

for i in df['學校名稱']:
    if ('國立' in i) or ('市立' in i):
        type_list.append('公立')
    else:
        type_list.append('私立')

df['公私立'] = type_list # 將 Dataframe 新增「公私立」column

df2 = df.drop_duplicates(subset="學校名稱")
count = df2['公私立'].value_counts()

print(df2)
print(f"本資料集共收集了 {len(df2)} 所學校，其中公立：{count['公立']} 所；私立：{count['私立']} 所。")

"""# 3. 各等級別學制共有？所

step1: 篩選掉重複的學校名稱與等級別 (drop_duplicates, subset)

step2: 計算出等級別的筆數 (value_counts)

step3: 建立等級別的字串，並找出其類別 (unique)

step4: 使用for迴圈，依序列出所有等級別學制的學校數量 (count)
"""

df3 = df.drop_duplicates(subset=['學校名稱','等級別'])
count = df3['等級別'].value_counts()
degree_list = list(df['等級別'].unique())

print(f"本資料集總共收集了 {len(set(df['學校名稱']))} 所學校，各等級學制當中：")
for degree in degree_list:
    print(f"一共有{count[degree]} 所學校， 有招收{degree[2:]}。")

"""# 4. 各縣市分別有？所，位於新北市的大專院校總共有幾所"""



"""# 5. 北中南東區分別有？所

都市及區域發展統計彙編 - 國發會 https://www.ndc.gov.tw/nc_77_4402

北部區域：包括臺北市、新北市、基隆市、新竹市、桃園市、新竹縣及宜蘭縣。

中部區域：包括臺中市、苗栗縣、彰化縣、南投縣及雲林縣。

南部區域：包括高雄市、臺南市、嘉義市、嘉義縣、屏東縣及澎湖縣。

東部區域：包括花蓮縣及臺東縣。

福建省：包括金門縣與連江縣。
"""



"""# 6. 各體系別分別有？所"""



"""# 7. 國立/私立與男女比
請問國立大學與私立大學在學男生女生比例為何? 延修生男生女生比例為何?
"""



"""# 8. 國立大學在學生男女比"""



""" # 9. 每校平均最多與最少人的體系"""



"""# 10. 將新增的欄位寫入並儲存成新的CSV檔案，並命名為112_students_tf.csv

新增的欄位有"公私立"，"縣市名"，"區域"
"""

